name: Deploy to Deno

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Allows authentication with Deno Deploy.
      contents: read # Allows cloning the repo.

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Cache Deno modules
        uses: actions/cache@v2
        with:
          path: ~/.cache/deno
          key: ${{ runner.os }}-deno-${{ hashFiles('**/*.ts') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Install dependencies
        run: deno cache main.tsx

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: yazganxyz-rehash-blog # the name of the project on Deno Deploy
          entrypoint: main.tsx
